backend:
  name: github
  branch: main
  repo: 'hlysine/quick-med'
  base_url: https://quick-med-auth.up.railway.app
  auth_endpoint: /auth
site_url: https://quick-med.up.railway.app
media_folder: 'public/assets'
public_folder: 'assets'
publish_mode: editorial_workflow
open_authoring: true
collections:
  - name: 'calc'
    label: 'Calculators'
    folder: 'src/content/calc'
    preview_path: 'calc/{{slug}}'
    create: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Section', name: 'section', widget: 'string' }
      - { label: 'Keywords', name: 'keywords', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'conditions'
    label: 'Conditions'
    folder: 'src/content/conditions'
    preview_path: 'conditions/{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Section', name: 'section', widget: 'string' }
      - { label: 'Keywords', name: 'keywords', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'investigations'
    label: 'Investigations'
    folder: 'src/content/investigations'
    preview_path: 'investigations/{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Section', name: 'section', widget: 'string' }
      - { label: 'Keywords', name: 'keywords', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'managements'
    label: 'Managements'
    folder: 'src/content/managements'
    preview_path: 'managements/{{slug}}'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Section', name: 'section', widget: 'string' }
      - { label: 'Keywords', name: 'keywords', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
