/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'
import { Route as IndexImport } from './routes/index'
import { Route as ManagementsIndexImport } from './routes/managements/index'
import { Route as InvestigationsIndexImport } from './routes/investigations/index'
import { Route as ConditionsIndexImport } from './routes/conditions/index'
import { Route as CalcIndexImport } from './routes/calc/index'
import { Route as ManagementsKeyImport } from './routes/managements/$key'
import { Route as InvestigationsKeyImport } from './routes/investigations/$key'
import { Route as DrugsSplatImport } from './routes/drugs.$'
import { Route as ConditionsKeyImport } from './routes/conditions/$key'
import { Route as CalcPeakFlowRateImport } from './routes/calc/peak-flow-rate'
import { Route as CalcOxygenGradientImport } from './routes/calc/oxygen-gradient'
import { Route as CalcMetabolicAlkalosisImport } from './routes/calc/metabolic-alkalosis'
import { Route as CalcMetabolicAcidosisImport } from './routes/calc/metabolic-acidosis'
import { Route as CalcGlasgowComaScaleImport } from './routes/calc/glasgow-coma-scale'
import { Route as CalcFluidPrescriptionImport } from './routes/calc/fluid-prescription'
import { Route as CalcCorrectedSodiumImport } from './routes/calc/corrected-sodium'
import { Route as CalcChronicRespiratoryAlkalosisImport } from './routes/calc/chronic-respiratory-alkalosis'
import { Route as CalcChronicRespiratoryAcidosisImport } from './routes/calc/chronic-respiratory-acidosis'
import { Route as CalcAnionGapImport } from './routes/calc/anion-gap'
import { Route as CalcAcuteRespiratoryAlkalosisImport } from './routes/calc/acute-respiratory-alkalosis'
import { Route as CalcAcuteRespiratoryAcidosisImport } from './routes/calc/acute-respiratory-acidosis'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementsIndexRoute = ManagementsIndexImport.update({
  id: '/managements/',
  path: '/managements/',
  getParentRoute: () => rootRoute,
} as any)

const InvestigationsIndexRoute = InvestigationsIndexImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsIndexRoute = ConditionsIndexImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRoute,
} as any)

const CalcIndexRoute = CalcIndexImport.update({
  id: '/calc/',
  path: '/calc/',
  getParentRoute: () => rootRoute,
} as any)

const ManagementsKeyRoute = ManagementsKeyImport.update({
  id: '/managements/$key',
  path: '/managements/$key',
  getParentRoute: () => rootRoute,
} as any)

const InvestigationsKeyRoute = InvestigationsKeyImport.update({
  id: '/investigations/$key',
  path: '/investigations/$key',
  getParentRoute: () => rootRoute,
} as any)

const DrugsSplatRoute = DrugsSplatImport.update({
  id: '/drugs/$',
  path: '/drugs/$',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsKeyRoute = ConditionsKeyImport.update({
  id: '/conditions/$key',
  path: '/conditions/$key',
  getParentRoute: () => rootRoute,
} as any)

const CalcPeakFlowRateRoute = CalcPeakFlowRateImport.update({
  id: '/calc/peak-flow-rate',
  path: '/calc/peak-flow-rate',
  getParentRoute: () => rootRoute,
} as any)

const CalcOxygenGradientRoute = CalcOxygenGradientImport.update({
  id: '/calc/oxygen-gradient',
  path: '/calc/oxygen-gradient',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAlkalosisRoute = CalcMetabolicAlkalosisImport.update({
  id: '/calc/metabolic-alkalosis',
  path: '/calc/metabolic-alkalosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcMetabolicAcidosisRoute = CalcMetabolicAcidosisImport.update({
  id: '/calc/metabolic-acidosis',
  path: '/calc/metabolic-acidosis',
  getParentRoute: () => rootRoute,
} as any)

const CalcGlasgowComaScaleRoute = CalcGlasgowComaScaleImport.update({
  id: '/calc/glasgow-coma-scale',
  path: '/calc/glasgow-coma-scale',
  getParentRoute: () => rootRoute,
} as any)

const CalcFluidPrescriptionRoute = CalcFluidPrescriptionImport.update({
  id: '/calc/fluid-prescription',
  path: '/calc/fluid-prescription',
  getParentRoute: () => rootRoute,
} as any)

const CalcCorrectedSodiumRoute = CalcCorrectedSodiumImport.update({
  id: '/calc/corrected-sodium',
  path: '/calc/corrected-sodium',
  getParentRoute: () => rootRoute,
} as any)

const CalcChronicRespiratoryAlkalosisRoute =
  CalcChronicRespiratoryAlkalosisImport.update({
    id: '/calc/chronic-respiratory-alkalosis',
    path: '/calc/chronic-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcChronicRespiratoryAcidosisRoute =
  CalcChronicRespiratoryAcidosisImport.update({
    id: '/calc/chronic-respiratory-acidosis',
    path: '/calc/chronic-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAnionGapRoute = CalcAnionGapImport.update({
  id: '/calc/anion-gap',
  path: '/calc/anion-gap',
  getParentRoute: () => rootRoute,
} as any)

const CalcAcuteRespiratoryAlkalosisRoute =
  CalcAcuteRespiratoryAlkalosisImport.update({
    id: '/calc/acute-respiratory-alkalosis',
    path: '/calc/acute-respiratory-alkalosis',
    getParentRoute: () => rootRoute,
  } as any)

const CalcAcuteRespiratoryAcidosisRoute =
  CalcAcuteRespiratoryAcidosisImport.update({
    id: '/calc/acute-respiratory-acidosis',
    path: '/calc/acute-respiratory-acidosis',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-acidosis': {
      id: '/calc/acute-respiratory-acidosis'
      path: '/calc/acute-respiratory-acidosis'
      fullPath: '/calc/acute-respiratory-acidosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/acute-respiratory-alkalosis': {
      id: '/calc/acute-respiratory-alkalosis'
      path: '/calc/acute-respiratory-alkalosis'
      fullPath: '/calc/acute-respiratory-alkalosis'
      preLoaderRoute: typeof CalcAcuteRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/anion-gap': {
      id: '/calc/anion-gap'
      path: '/calc/anion-gap'
      fullPath: '/calc/anion-gap'
      preLoaderRoute: typeof CalcAnionGapImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-acidosis': {
      id: '/calc/chronic-respiratory-acidosis'
      path: '/calc/chronic-respiratory-acidosis'
      fullPath: '/calc/chronic-respiratory-acidosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/chronic-respiratory-alkalosis': {
      id: '/calc/chronic-respiratory-alkalosis'
      path: '/calc/chronic-respiratory-alkalosis'
      fullPath: '/calc/chronic-respiratory-alkalosis'
      preLoaderRoute: typeof CalcChronicRespiratoryAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/corrected-sodium': {
      id: '/calc/corrected-sodium'
      path: '/calc/corrected-sodium'
      fullPath: '/calc/corrected-sodium'
      preLoaderRoute: typeof CalcCorrectedSodiumImport
      parentRoute: typeof rootRoute
    }
    '/calc/fluid-prescription': {
      id: '/calc/fluid-prescription'
      path: '/calc/fluid-prescription'
      fullPath: '/calc/fluid-prescription'
      preLoaderRoute: typeof CalcFluidPrescriptionImport
      parentRoute: typeof rootRoute
    }
    '/calc/glasgow-coma-scale': {
      id: '/calc/glasgow-coma-scale'
      path: '/calc/glasgow-coma-scale'
      fullPath: '/calc/glasgow-coma-scale'
      preLoaderRoute: typeof CalcGlasgowComaScaleImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-acidosis': {
      id: '/calc/metabolic-acidosis'
      path: '/calc/metabolic-acidosis'
      fullPath: '/calc/metabolic-acidosis'
      preLoaderRoute: typeof CalcMetabolicAcidosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/metabolic-alkalosis': {
      id: '/calc/metabolic-alkalosis'
      path: '/calc/metabolic-alkalosis'
      fullPath: '/calc/metabolic-alkalosis'
      preLoaderRoute: typeof CalcMetabolicAlkalosisImport
      parentRoute: typeof rootRoute
    }
    '/calc/oxygen-gradient': {
      id: '/calc/oxygen-gradient'
      path: '/calc/oxygen-gradient'
      fullPath: '/calc/oxygen-gradient'
      preLoaderRoute: typeof CalcOxygenGradientImport
      parentRoute: typeof rootRoute
    }
    '/calc/peak-flow-rate': {
      id: '/calc/peak-flow-rate'
      path: '/calc/peak-flow-rate'
      fullPath: '/calc/peak-flow-rate'
      preLoaderRoute: typeof CalcPeakFlowRateImport
      parentRoute: typeof rootRoute
    }
    '/conditions/$key': {
      id: '/conditions/$key'
      path: '/conditions/$key'
      fullPath: '/conditions/$key'
      preLoaderRoute: typeof ConditionsKeyImport
      parentRoute: typeof rootRoute
    }
    '/drugs/$': {
      id: '/drugs/$'
      path: '/drugs/$'
      fullPath: '/drugs/$'
      preLoaderRoute: typeof DrugsSplatImport
      parentRoute: typeof rootRoute
    }
    '/investigations/$key': {
      id: '/investigations/$key'
      path: '/investigations/$key'
      fullPath: '/investigations/$key'
      preLoaderRoute: typeof InvestigationsKeyImport
      parentRoute: typeof rootRoute
    }
    '/managements/$key': {
      id: '/managements/$key'
      path: '/managements/$key'
      fullPath: '/managements/$key'
      preLoaderRoute: typeof ManagementsKeyImport
      parentRoute: typeof rootRoute
    }
    '/calc/': {
      id: '/calc/'
      path: '/calc'
      fullPath: '/calc'
      preLoaderRoute: typeof CalcIndexImport
      parentRoute: typeof rootRoute
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsIndexImport
      parentRoute: typeof rootRoute
    }
    '/investigations/': {
      id: '/investigations/'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/managements/': {
      id: '/managements/'
      path: '/managements'
      fullPath: '/managements'
      preLoaderRoute: typeof ManagementsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/fluid-prescription': typeof CalcFluidPrescriptionRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$': typeof DrugsSplatRoute
  '/investigations/$key': typeof InvestigationsKeyRoute
  '/managements/$key': typeof ManagementsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/managements': typeof ManagementsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/fluid-prescription': typeof CalcFluidPrescriptionRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$': typeof DrugsSplatRoute
  '/investigations/$key': typeof InvestigationsKeyRoute
  '/managements/$key': typeof ManagementsKeyRoute
  '/calc': typeof CalcIndexRoute
  '/conditions': typeof ConditionsIndexRoute
  '/investigations': typeof InvestigationsIndexRoute
  '/managements': typeof ManagementsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsLazyRoute
  '/calc/acute-respiratory-acidosis': typeof CalcAcuteRespiratoryAcidosisRoute
  '/calc/acute-respiratory-alkalosis': typeof CalcAcuteRespiratoryAlkalosisRoute
  '/calc/anion-gap': typeof CalcAnionGapRoute
  '/calc/chronic-respiratory-acidosis': typeof CalcChronicRespiratoryAcidosisRoute
  '/calc/chronic-respiratory-alkalosis': typeof CalcChronicRespiratoryAlkalosisRoute
  '/calc/corrected-sodium': typeof CalcCorrectedSodiumRoute
  '/calc/fluid-prescription': typeof CalcFluidPrescriptionRoute
  '/calc/glasgow-coma-scale': typeof CalcGlasgowComaScaleRoute
  '/calc/metabolic-acidosis': typeof CalcMetabolicAcidosisRoute
  '/calc/metabolic-alkalosis': typeof CalcMetabolicAlkalosisRoute
  '/calc/oxygen-gradient': typeof CalcOxygenGradientRoute
  '/calc/peak-flow-rate': typeof CalcPeakFlowRateRoute
  '/conditions/$key': typeof ConditionsKeyRoute
  '/drugs/$': typeof DrugsSplatRoute
  '/investigations/$key': typeof InvestigationsKeyRoute
  '/managements/$key': typeof ManagementsKeyRoute
  '/calc/': typeof CalcIndexRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/investigations/': typeof InvestigationsIndexRoute
  '/managements/': typeof ManagementsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/settings'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/fluid-prescription'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$'
    | '/investigations/$key'
    | '/managements/$key'
    | '/calc'
    | '/conditions'
    | '/investigations'
    | '/managements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/settings'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/fluid-prescription'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$'
    | '/investigations/$key'
    | '/managements/$key'
    | '/calc'
    | '/conditions'
    | '/investigations'
    | '/managements'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/settings'
    | '/calc/acute-respiratory-acidosis'
    | '/calc/acute-respiratory-alkalosis'
    | '/calc/anion-gap'
    | '/calc/chronic-respiratory-acidosis'
    | '/calc/chronic-respiratory-alkalosis'
    | '/calc/corrected-sodium'
    | '/calc/fluid-prescription'
    | '/calc/glasgow-coma-scale'
    | '/calc/metabolic-acidosis'
    | '/calc/metabolic-alkalosis'
    | '/calc/oxygen-gradient'
    | '/calc/peak-flow-rate'
    | '/conditions/$key'
    | '/drugs/$'
    | '/investigations/$key'
    | '/managements/$key'
    | '/calc/'
    | '/conditions/'
    | '/investigations/'
    | '/managements/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  CalcAcuteRespiratoryAcidosisRoute: typeof CalcAcuteRespiratoryAcidosisRoute
  CalcAcuteRespiratoryAlkalosisRoute: typeof CalcAcuteRespiratoryAlkalosisRoute
  CalcAnionGapRoute: typeof CalcAnionGapRoute
  CalcChronicRespiratoryAcidosisRoute: typeof CalcChronicRespiratoryAcidosisRoute
  CalcChronicRespiratoryAlkalosisRoute: typeof CalcChronicRespiratoryAlkalosisRoute
  CalcCorrectedSodiumRoute: typeof CalcCorrectedSodiumRoute
  CalcFluidPrescriptionRoute: typeof CalcFluidPrescriptionRoute
  CalcGlasgowComaScaleRoute: typeof CalcGlasgowComaScaleRoute
  CalcMetabolicAcidosisRoute: typeof CalcMetabolicAcidosisRoute
  CalcMetabolicAlkalosisRoute: typeof CalcMetabolicAlkalosisRoute
  CalcOxygenGradientRoute: typeof CalcOxygenGradientRoute
  CalcPeakFlowRateRoute: typeof CalcPeakFlowRateRoute
  ConditionsKeyRoute: typeof ConditionsKeyRoute
  DrugsSplatRoute: typeof DrugsSplatRoute
  InvestigationsKeyRoute: typeof InvestigationsKeyRoute
  ManagementsKeyRoute: typeof ManagementsKeyRoute
  CalcIndexRoute: typeof CalcIndexRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  InvestigationsIndexRoute: typeof InvestigationsIndexRoute
  ManagementsIndexRoute: typeof ManagementsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  CalcAcuteRespiratoryAcidosisRoute: CalcAcuteRespiratoryAcidosisRoute,
  CalcAcuteRespiratoryAlkalosisRoute: CalcAcuteRespiratoryAlkalosisRoute,
  CalcAnionGapRoute: CalcAnionGapRoute,
  CalcChronicRespiratoryAcidosisRoute: CalcChronicRespiratoryAcidosisRoute,
  CalcChronicRespiratoryAlkalosisRoute: CalcChronicRespiratoryAlkalosisRoute,
  CalcCorrectedSodiumRoute: CalcCorrectedSodiumRoute,
  CalcFluidPrescriptionRoute: CalcFluidPrescriptionRoute,
  CalcGlasgowComaScaleRoute: CalcGlasgowComaScaleRoute,
  CalcMetabolicAcidosisRoute: CalcMetabolicAcidosisRoute,
  CalcMetabolicAlkalosisRoute: CalcMetabolicAlkalosisRoute,
  CalcOxygenGradientRoute: CalcOxygenGradientRoute,
  CalcPeakFlowRateRoute: CalcPeakFlowRateRoute,
  ConditionsKeyRoute: ConditionsKeyRoute,
  DrugsSplatRoute: DrugsSplatRoute,
  InvestigationsKeyRoute: InvestigationsKeyRoute,
  ManagementsKeyRoute: ManagementsKeyRoute,
  CalcIndexRoute: CalcIndexRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  InvestigationsIndexRoute: InvestigationsIndexRoute,
  ManagementsIndexRoute: ManagementsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search",
        "/settings",
        "/calc/acute-respiratory-acidosis",
        "/calc/acute-respiratory-alkalosis",
        "/calc/anion-gap",
        "/calc/chronic-respiratory-acidosis",
        "/calc/chronic-respiratory-alkalosis",
        "/calc/corrected-sodium",
        "/calc/fluid-prescription",
        "/calc/glasgow-coma-scale",
        "/calc/metabolic-acidosis",
        "/calc/metabolic-alkalosis",
        "/calc/oxygen-gradient",
        "/calc/peak-flow-rate",
        "/conditions/$key",
        "/drugs/$",
        "/investigations/$key",
        "/managements/$key",
        "/calc/",
        "/conditions/",
        "/investigations/",
        "/managements/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    },
    "/calc/acute-respiratory-acidosis": {
      "filePath": "calc/acute-respiratory-acidosis.tsx"
    },
    "/calc/acute-respiratory-alkalosis": {
      "filePath": "calc/acute-respiratory-alkalosis.tsx"
    },
    "/calc/anion-gap": {
      "filePath": "calc/anion-gap.tsx"
    },
    "/calc/chronic-respiratory-acidosis": {
      "filePath": "calc/chronic-respiratory-acidosis.tsx"
    },
    "/calc/chronic-respiratory-alkalosis": {
      "filePath": "calc/chronic-respiratory-alkalosis.tsx"
    },
    "/calc/corrected-sodium": {
      "filePath": "calc/corrected-sodium.tsx"
    },
    "/calc/fluid-prescription": {
      "filePath": "calc/fluid-prescription.tsx"
    },
    "/calc/glasgow-coma-scale": {
      "filePath": "calc/glasgow-coma-scale.tsx"
    },
    "/calc/metabolic-acidosis": {
      "filePath": "calc/metabolic-acidosis.tsx"
    },
    "/calc/metabolic-alkalosis": {
      "filePath": "calc/metabolic-alkalosis.tsx"
    },
    "/calc/oxygen-gradient": {
      "filePath": "calc/oxygen-gradient.tsx"
    },
    "/calc/peak-flow-rate": {
      "filePath": "calc/peak-flow-rate.tsx"
    },
    "/conditions/$key": {
      "filePath": "conditions/$key.tsx"
    },
    "/drugs/$": {
      "filePath": "drugs.$.tsx"
    },
    "/investigations/$key": {
      "filePath": "investigations/$key.tsx"
    },
    "/managements/$key": {
      "filePath": "managements/$key.tsx"
    },
    "/calc/": {
      "filePath": "calc/index.tsx"
    },
    "/conditions/": {
      "filePath": "conditions/index.tsx"
    },
    "/investigations/": {
      "filePath": "investigations/index.tsx"
    },
    "/managements/": {
      "filePath": "managements/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
